
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Code, Zap, FileCode, Terminal } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface AutonomousCodeGeneratorProps {
  module: DevelopmentModule;
}

export const AutonomousCodeGenerator: React.FC<AutonomousCodeGeneratorProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-purple-600/20 to-pink-600/20 border-purple-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-purple-300">
          <div className="flex items-center">
            <Code className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-purple-400 border-purple-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Terminal className="h-4 w-4 mr-2" />
            Auto-Generation Status
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Generating React components automatically</p>
            <p>• Building TypeScript interfaces</p>
            <p>• Creating API integration code</p>
            <p>• Optimizing performance algorithms</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <FileCode className="h-4 w-4 mr-2" />
            Generated Capabilities
          </h4>
          <div className="flex flex-wrap gap-1">
            {module.capabilities.slice(0, 4).map((capability, index) => (
              <Badge key={index} variant="outline" className="text-xs text-cyan-400 border-cyan-400">
                {capability}
              </Badge>
            ))}
            {module.capabilities.length > 4 && (
              <Badge variant="outline" className="text-xs text-gray-400 border-gray-400">
                +{module.capabilities.length - 4} more
              </Badge>
            )}
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-green-400 text-sm">
            <Zap className="h-4 w-4 mr-2" />
            MIORA is autonomously writing code...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Last activity: {new Date(module.lastActivity).toLocaleTimeString()}
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
