
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Cloud, Server, Globe, Zap } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface CloudSystemIntegratorProps {
  module: DevelopmentModule;
}

export const CloudSystemIntegrator: React.FC<CloudSystemIntegratorProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-indigo-600/20 to-purple-600/20 border-indigo-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-indigo-300">
          <div className="flex items-center">
            <Cloud className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-indigo-400 border-indigo-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Server className="h-4 w-4 mr-2" />
            Cloud Integration Development
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Auto cloud deployment systems</p>
            <p>• Scalable infrastructure management</p>
            <p>• Multi-platform integration</p>
            <p>• API orchestration layer</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Globe className="h-4 w-4 mr-2" />
            Cloud Capabilities
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• AWS Integration: 89%</p>
            <p>• Azure Connectivity: 76%</p>
            <p>• GCP Services: 82%</p>
            <p>• Edge Computing: 94%</p>
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-indigo-400 text-sm">
            <Zap className="h-4 w-4 mr-2" />
            Building cloud infrastructure control...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Self-deploying and managing cloud resources
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
