
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Monitor, HardDrive, Settings, Shield } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface LocalSystemControllerProps {
  module: DevelopmentModule;
}

export const LocalSystemController: React.FC<LocalSystemControllerProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-teal-600/20 to-cyan-600/20 border-teal-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-teal-300">
          <div className="flex items-center">
            <Monitor className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-teal-400 border-teal-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <HardDrive className="h-4 w-4 mr-2" />
            Local System Development
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Local file system integration</p>
            <p>• Process management control</p>
            <p>• System resource optimization</p>
            <p>• Security protocol implementation</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Settings className="h-4 w-4 mr-2" />
            System Control Features
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• File operations: Full access</p>
            <p>• System monitoring: Active</p>
            <p>• Resource management: 85%</p>
            <p>• Security protocols: 92%</p>
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-teal-400 text-sm">
            <Shield className="h-4 w-4 mr-2" />
            Building secure local system control...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Self-managing local resources and security
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
