
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Database, HardDrive, Infinity, Cpu } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface MemoryAIArchitectProps {
  module: DevelopmentModule;
}

export const MemoryAIArchitect: React.FC<MemoryAIArchitectProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-orange-600/20 to-red-600/20 border-orange-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-orange-300">
          <div className="flex items-center">
            <Database className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-orange-400 border-orange-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <HardDrive className="h-4 w-4 mr-2" />
            Memory Architecture Development
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Infinite memory structure design</p>
            <p>• Pattern-based storage system</p>
            <p>• Instant retrieval algorithms</p>
            <p>• Contextual memory linking</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Infinity className="h-4 w-4 mr-2" />
            Memory Capabilities
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Long-term memory: Unlimited</p>
            <p>• Pattern recognition: 96%</p>
            <p>• Memory compression: 91%</p>
            <p>• Cross-reference linking: 88%</p>
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-orange-400 text-sm">
            <Cpu className="h-4 w-4 mr-2" />
            Building infinite memory architecture...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Self-optimizing storage and retrieval systems
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
