
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Brain, MessageSquare, Languages, Sparkles } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface NLPEngineBuilderProps {
  module: DevelopmentModule;
}

export const NLPEngineBuilder: React.FC<NLPEngineBuilderProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-cyan-600/20 to-blue-600/20 border-cyan-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-cyan-300">
          <div className="flex items-center">
            <Brain className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-cyan-400 border-cyan-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <MessageSquare className="h-4 w-4 mr-2" />
            NLP Development Status
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Building advanced language models</p>
            <p>• Training context understanding</p>
            <p>• Developing semantic analysis</p>
            <p>• Creating conversation patterns</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Languages className="h-4 w-4 mr-2" />
            Language Capabilities
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Indonesian: Advanced (98%)</p>
            <p>• English: Advanced (95%)</p>
            <p>• Multi-language: Developing (87%)</p>
            <p>• Emotional Intelligence: Active (92%)</p>
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-blue-400 text-sm">
            <Sparkles className="h-4 w-4 mr-2" />
            Building NLP beyond GPT capabilities...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Self-optimizing language processing engine
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
