
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Mic, Volume2, Radio, Headphones } from 'lucide-react';

interface DevelopmentModule {
  id: string;
  name: string;
  status: 'active' | 'developing' | 'standby' | 'error';
  progress: number;
  autoGenerated: boolean;
  capabilities: string[];
  lastActivity: number;
}

interface VoiceCommunicationCoreProps {
  module: DevelopmentModule;
}

export const VoiceCommunicationCore: React.FC<VoiceCommunicationCoreProps> = ({ module }) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-500';
      case 'developing': return 'bg-blue-500';
      case 'standby': return 'bg-yellow-500';
      case 'error': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  return (
    <Card className="bg-gradient-to-br from-green-600/20 to-emerald-600/20 border-green-500/30">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-green-300">
          <div className="flex items-center">
            <Mic className="h-5 w-5 mr-2" />
            {module.name}
          </div>
          <div className="flex items-center space-x-2">
            <div className={`w-2 h-2 rounded-full ${getStatusColor(module.status)}`}></div>
            <Badge variant="outline" className="text-green-400 border-green-400">
              {module.status.toUpperCase()}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Progress value={module.progress} className="h-2" />
        <p className="text-sm text-gray-300">Progress: {module.progress.toFixed(1)}%</p>
        
        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Volume2 className="h-4 w-4 mr-2" />
            Voice System Development
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Advanced speech recognition engine</p>
            <p>• Natural voice synthesis system</p>
            <p>• Real-time audio processing</p>
            <p>• Emotion detection in voice</p>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-white font-medium flex items-center">
            <Radio className="h-4 w-4 mr-2" />
            Communication Features
          </h4>
          <div className="space-y-1 text-xs text-gray-300">
            <p>• Two-way conversation: Active</p>
            <p>• Voice command processing: 94%</p>
            <p>• Ambient noise filtering: 89%</p>
            <p>• Multi-device synchronization: 78%</p>
          </div>
        </div>

        <div className="mt-4 p-3 bg-black/30 rounded">
          <div className="flex items-center text-green-400 text-sm">
            <Headphones className="h-4 w-4 mr-2" />
            Building advanced voice communication...
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Self-developing audio processing algorithms
          </p>
        </div>
      </CardContent>
    </Card>
  );
};
