// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giedmjqlombvvsdlqlwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZWRtanFsb21idnZzZGxxbHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTQ0MzksImV4cCI6MjA2ODk5MDQzOX0.pXk8xy46FX1Dot25exFWvIlpZEFEfji9_5Bv7ApTMgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});